<?php
/**
 * PDF Generator for TruePaws
 * Uses Dompdf to convert HTML to PDF
 */

if (!defined('ABSPATH')) {
    exit;
}

class TruePaws_PDF_Generator {

    /**
     * Check if Dompdf is available
     */
    public static function is_dompdf_available() {
        return class_exists('\Dompdf\Dompdf');
    }

    /**
     * Generate pedigree PDF
     * Note: For MVP, this creates a simple HTML-based pedigree that can be printed
     */
    public static function generate_pedigree_pdf($animal_id, $generations = 3) {
        $pedigree = truepaws_get_pedigree($animal_id, $generations);

        if (!$pedigree) {
            return false;
        }

        // For MVP, create HTML output that can be printed as PDF
        // In production, integrate with TCPDF or similar library
        ob_start();
        ?>
        <!DOCTYPE html>
        <html>
        <head>
            <title>Pedigree - <?php echo esc_html($pedigree['animal']['name']); ?></title>
            <style>
                body { font-family: Arial, sans-serif; margin: 20px; }
                .header { text-align: center; margin-bottom: 30px; }
                .pedigree-tree { display: flex; flex-direction: column; align-items: center; }
                .pedigree-generation { display: flex; justify-content: center; margin: 20px 0; }
                .pedigree-animal { border: 2px solid #333; padding: 10px; margin: 0 5px; text-align: center; min-width: 150px; }
                .pedigree-animal.main { border-color: #0066cc; background: #f0f7ff; }
                .animal-name { font-weight: bold; }
                .animal-reg { font-size: 12px; color: #666; }
                .footer { margin-top: 50px; text-align: center; font-size: 12px; color: #666; }
            </style>
        </head>
        <body>
            <div class="header">
                <h1>TruePaws Pedigree Certificate</h1>
                <h2><?php echo esc_html($pedigree['animal']['name']); ?></h2>
                <?php if (!empty($pedigree['animal']['registration_number'])): ?>
                    <p>Registration: <?php echo esc_html($pedigree['animal']['registration_number']); ?></p>
                <?php endif; ?>
                <?php if (!empty($pedigree['animal']['birth_date'])): ?>
                    <p>Born: <?php echo esc_html(date('F j, Y', strtotime($pedigree['animal']['birth_date']))); ?></p>
                <?php endif; ?>
            </div>

            <div class="pedigree-tree">
                <div class="pedigree-generation">
                    <div class="pedigree-animal main">
                        <div class="animal-name"><?php echo esc_html($pedigree['animal']['name']); ?></div>
                        <?php if (!empty($pedigree['animal']['registration_number'])): ?>
                            <div class="animal-reg"><?php echo esc_html($pedigree['animal']['registration_number']); ?></div>
                        <?php endif; ?>
                    </div>
                </div>

                <?php if (!empty($pedigree['generations']['sire']) || !empty($pedigree['generations']['dam'])): ?>
                <div class="pedigree-generation">
                    <div class="pedigree-animal">
                        <div class="animal-name">Sire</div>
                        <?php if (!empty($pedigree['generations']['sire'])): ?>
                            <div class="animal-name"><?php echo esc_html($pedigree['generations']['sire']['name']); ?></div>
                            <?php if (!empty($pedigree['generations']['sire']['registration_number'])): ?>
                                <div class="animal-reg"><?php echo esc_html($pedigree['generations']['sire']['registration_number']); ?></div>
                            <?php endif; ?>
                        <?php else: ?>
                            <div class="animal-name">Unknown</div>
                        <?php endif; ?>
                    </div>
                    <div class="pedigree-animal">
                        <div class="animal-name">Dam</div>
                        <?php if (!empty($pedigree['generations']['dam'])): ?>
                            <div class="animal-name"><?php echo esc_html($pedigree['generations']['dam']['name']); ?></div>
                            <?php if (!empty($pedigree['generations']['dam']['registration_number'])): ?>
                                <div class="animal-reg"><?php echo esc_html($pedigree['generations']['dam']['registration_number']); ?></div>
                            <?php endif; ?>
                        <?php else: ?>
                            <div class="animal-name">Unknown</div>
                        <?php endif; ?>
                    </div>
                </div>
                <?php endif; ?>
            </div>

            <div class="footer">
                <p>Generated by TruePaws Kennel Management System on <?php echo date('F j, Y \a\t g:i A'); ?></p>
                <p>Print this page to create a PDF pedigree certificate</p>
            </div>
        </body>
        </html>
        <?php

        $html = ob_get_clean();

        // For MVP, we'll output HTML that can be printed as PDF
        // In production, use a proper PDF library
        header('Content-Type: text/html');
        header('Content-Disposition: attachment; filename="pedigree-' . sanitize_title($pedigree['animal']['name']) . '-' . date('Y-m-d') . '.html"');
        echo $html;
        exit;
    }

    /**
     * Draw pedigree tree on PDF
     */
    private static function draw_pedigree_tree($pdf, $pedigree, $x = 10, $y = 60, $width = 180, $depth = 0) {
        $max_depth = 3;

        if ($depth > $max_depth) {
            return;
        }

        // Draw main animal box
        $pdf->SetFillColor(240, 240, 240);
        $pdf->Rect($x + $width/2 - 40, $y, 80, 20, 'DF');

        $pdf->SetFont('helvetica', 'B', 10);
        $pdf->SetXY($x + $width/2 - 35, $y + 2);
        $pdf->Cell(70, 5, substr($pedigree['animal']['name'], 0, 20), 0, 0, 'C');

        if ($depth < $max_depth) {
            // Draw parent boxes
            $parent_y = $y + 25;
            $parent_width = $width / 2;

            // Sire
            if (!empty($pedigree['generations']['sire'])) {
                self::draw_parent_box($pdf, $pedigree['generations']['sire'], $x, $parent_y, $parent_width, $depth + 1);
            } else {
                $pdf->Rect($x + 5, $parent_y, $parent_width - 10, 15);
                $pdf->SetXY($x + 10, $parent_y + 2);
                $pdf->Cell($parent_width - 20, 5, 'Unknown', 0, 0, 'C');
            }

            // Dam
            if (!empty($pedigree['generations']['dam'])) {
                self::draw_parent_box($pdf, $pedigree['generations']['dam'], $x + $parent_width, $parent_y, $parent_width, $depth + 1);
            } else {
                $pdf->Rect($x + $parent_width + 5, $parent_y, $parent_width - 10, 15);
                $pdf->SetXY($x + $parent_width + 10, $parent_y + 2);
                $pdf->Cell($parent_width - 20, 5, 'Unknown', 0, 0, 'C');
            }

            // Draw connecting lines
            $pdf->Line($x + $width/2, $y + 20, $x + $parent_width/2, $parent_y);
            $pdf->Line($x + $width/2, $y + 20, $x + $parent_width + $parent_width/2, $parent_y);
        }
    }

    /**
     * Draw parent box recursively
     */
    private static function draw_parent_box($pdf, $animal, $x, $y, $width, $depth) {
        $pdf->Rect($x + 5, $y, $width - 10, 15);
        $pdf->SetXY($x + 10, $y + 2);
        $pdf->SetFont('helvetica', '', 8);
        $pdf->Cell($width - 20, 4, substr($animal['name'], 0, 15), 0, 1, 'C');

        if (!empty($animal['registration_number'])) {
            $pdf->SetXY($x + 10, $y + 6);
            $pdf->SetFont('helvetica', '', 6);
            $pdf->Cell($width - 20, 3, substr($animal['registration_number'], 0, 20), 0, 0, 'C');
        }

        // Recursively draw grandparents if they exist
        if ($depth < 3 && (!empty($animal['descendants']['sire']) || !empty($animal['descendants']['dam']))) {
            $grandparent_y = $y + 18;
            $grandparent_width = $width / 2;

            // Draw grandparents (simplified)
            if (!empty($animal['descendants']['sire'])) {
                $pdf->Rect($x + 8, $grandparent_y, $grandparent_width - 11, 12);
                $pdf->SetXY($x + 10, $grandparent_y + 1);
                $pdf->SetFont('helvetica', '', 6);
                $pdf->Cell($grandparent_width - 15, 3, substr($animal['descendants']['sire']['name'], 0, 12), 0, 0, 'C');
            }

            if (!empty($animal['descendants']['dam'])) {
                $pdf->Rect($x + $grandparent_width + 3, $grandparent_y, $grandparent_width - 11, 12);
                $pdf->SetXY($x + $grandparent_width + 5, $grandparent_y + 1);
                $pdf->SetFont('helvetica', '', 6);
                $pdf->Cell($grandparent_width - 15, 3, substr($animal['descendants']['dam']['name'], 0, 12), 0, 0, 'C');
            }
        }
    }

    /**
     * Generate handover PDF
     * For MVP, creates HTML that can be printed as PDF
     */
    public static function generate_handover_pdf($animal_id) {
        global $wpdb;

        // Get animal data
        $animal = $wpdb->get_row(
            $wpdb->prepare(
                "SELECT A.*, S.name as sire_name, D.name as dam_name
                 FROM {$wpdb->prefix}bm_animals A
                 LEFT JOIN {$wpdb->prefix}bm_animals S ON A.sire_id = S.id
                 LEFT JOIN {$wpdb->prefix}bm_animals D ON A.dam_id = D.id
                 WHERE A.id = %d",
                $animal_id
            ),
            ARRAY_A
        );

        if (!$animal) {
            return false;
        }

        // Get health history (events)
        $events = $wpdb->get_results(
            $wpdb->prepare(
                "SELECT * FROM {$wpdb->prefix}bm_events
                 WHERE animal_id = %d AND event_type IN ('vaccine', 'vet_visit', 'heat', 'weight', 'birth')
                 ORDER BY event_date DESC",
                $animal_id
            ),
            ARRAY_A
        );

        ob_start();
        ?>
        <!DOCTYPE html>
        <html>
        <head>
            <title>Owner Handover - <?php echo esc_html($animal['name']); ?></title>
            <style>
                body { font-family: Arial, sans-serif; margin: 0; padding: 20px; line-height: 1.6; }
                .header { text-align: center; border-bottom: 2px solid #0066cc; padding-bottom: 20px; margin-bottom: 30px; }
                .section { margin-bottom: 30px; }
                .section h2 { color: #0066cc; border-bottom: 1px solid #ddd; padding-bottom: 5px; }
                .animal-info { background: #f8f9fa; padding: 15px; margin: 20px 0; }
                .health-table { width: 100%; border-collapse: collapse; margin: 20px 0; }
                .health-table th, .health-table td { border: 1px solid #ddd; padding: 8px; text-align: left; }
                .health-table th { background: #f8f9fa; font-weight: bold; }
                .pedigree { text-align: center; margin: 20px 0; }
                .footer { margin-top: 50px; text-align: center; font-size: 12px; color: #666; border-top: 1px solid #ddd; padding-top: 20px; }
                .print-note { background: #fff3cd; border: 1px solid #ffeeba; padding: 15px; margin: 20px 0; }
            </style>
        </head>
        <body>
            <div class="header">
                <h1>TruePaws Owner Handover</h1>
                <h2>Puppy: <?php echo esc_html($animal['name']); ?></h2>
                <p>Handover Date: <?php echo date('F j, Y'); ?></p>
            </div>

            <div class="section animal-info">
                <h2>Animal Information</h2>
                <p><strong>Name:</strong> <?php echo esc_html($animal['name']); ?></p>
                <?php if (!empty($animal['call_name'])): ?>
                    <p><strong>Call Name:</strong> <?php echo esc_html($animal['call_name']); ?></p>
                <?php endif; ?>
                <p><strong>Breed:</strong> <?php echo esc_html($animal['breed'] ?: 'Not specified'); ?></p>
                <p><strong>Sex:</strong> <?php echo $animal['sex'] === 'M' ? 'Male' : 'Female'; ?></p>
                <?php if (!empty($animal['birth_date'])): ?>
                    <p><strong>Date of Birth:</strong> <?php echo esc_html(date('F j, Y', strtotime($animal['birth_date']))); ?></p>
                <?php endif; ?>
                <?php if (!empty($animal['registration_number'])): ?>
                    <p><strong>Registration:</strong> <?php echo esc_html($animal['registration_number']); ?></p>
                <?php endif; ?>
                <p><strong>Sire:</strong> <?php echo esc_html($animal['sire_name'] ?: 'Unknown'); ?></p>
                <p><strong>Dam:</strong> <?php echo esc_html($animal['dam_name'] ?: 'Unknown'); ?></p>
            </div>

            <div class="section pedigree">
                <h2>Pedigree</h2>
                <div style="font-family: monospace; background: #f8f9fa; padding: 20px;">
                    <div><?php echo esc_html($animal['name']); ?></div>
                    <div style="margin-top: 10px;">
                        <span>Sire: <?php echo esc_html($animal['sire_name'] ?: 'Unknown'); ?></span>
                        <span style="margin-left: 20px;">Dam: <?php echo esc_html($animal['dam_name'] ?: 'Unknown'); ?></span>
                    </div>
                </div>
                <p><em>For complete 3-4 generation pedigree, see attached pedigree certificate.</em></p>
            </div>

            <div class="section">
                <h2>Health History</h2>
                <?php if (!empty($events)): ?>
                    <table class="health-table">
                        <thead>
                            <tr>
                                <th>Date</th>
                                <th>Event Type</th>
                                <th>Details</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($events as $event): ?>
                                <tr>
                                    <td><?php echo esc_html(date('M j, Y', strtotime($event['event_date']))); ?></td>
                                    <td><?php echo esc_html(ucfirst(str_replace('_', ' ', $event['event_type']))); ?></td>
                                    <td><?php echo esc_html($event['title']); ?></td>
                                </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                <?php else: ?>
                    <p>No health records available yet.</p>
                <?php endif; ?>
            </div>

            <div class="section">
                <h2>Care Instructions</h2>
                <?php
                $feeding_instructions = get_option('truepaws_feeding_instructions', '');
                if ($feeding_instructions):
                ?>
                    <div style="background: #f8f9fa; padding: 15px; margin: 20px 0;">
                        <?php echo wp_kses_post($feeding_instructions); ?>
                    </div>
                <?php else: ?>
                    <p>Please consult with your veterinarian for specific feeding recommendations based on your puppy's breed, age, and health needs.</p>
                <?php endif; ?>

                <h3>General Care Recommendations:</h3>
                <ul>
                    <li>Schedule a veterinary check-up within the first week</li>
                    <li>Maintain a consistent feeding schedule</li>
                    <li>Provide plenty of fresh water</li>
                    <li>Begin socialization and training early</li>
                    <li>Keep up with vaccination and parasite prevention schedules</li>
                    <li>Provide appropriate exercise and mental stimulation</li>
                </ul>
            </div>

            <div class="section">
                <h2>Contract & Terms</h2>
                <div style="background: #f8f9fa; padding: 20px; border-left: 4px solid #0066cc;">
                    <p><strong>Health Guarantee:</strong> This puppy is guaranteed to be in good health at the time of sale. Any congenital health issues will be addressed according to our health guarantee policy.</p>

                    <p><strong>Return Policy:</strong> If for any reason you cannot keep this puppy, please contact us immediately. We will work with you to find a suitable solution.</p>

                    <p><strong>Support:</strong> We are here to support you throughout your puppy's life. Please don't hesitate to contact us with any questions or concerns.</p>

                    <p><strong>Agreement:</strong> By accepting this puppy, you agree to provide proper care, veterinary attention, and a loving home.</p>
                </div>
            </div>

            <div class="footer">
                <p>Generated by TruePaws Kennel Management System on <?php echo date('F j, Y \a\t g:i A'); ?></p>
                <p>Thank you for choosing our kennel!</p>
            </div>
        </body>
        </html>
        <?php

        $html = ob_get_clean();

        if (self::is_dompdf_available()) {
            try {
                $dompdf = new \Dompdf\Dompdf();
                $dompdf->loadHtml($html);
                $dompdf->setPaper('A4', 'portrait');
                $dompdf->render();
                $pdf_output = $dompdf->output();

                return array(
                    'pdf' => base64_encode($pdf_output),
                    'filename' => 'handover-' . sanitize_title($animal['name']) . '-' . date('Y-m-d') . '.pdf'
                );
            } catch (Exception $e) {
                // Fallback to HTML if PDF generation fails
                return array(
                    'html' => $html,
                    'filename' => 'handover-' . sanitize_title($animal['name']) . '-' . date('Y-m-d') . '.html'
                );
            }
        }

        return array(
            'html' => $html,
            'filename' => 'handover-' . sanitize_title($animal['name']) . '-' . date('Y-m-d') . '.html'
        );
    }

    /**
     * Draw handover cover page
     */
    private static function draw_handover_cover($pdf, $animal) {
        // Title
        $pdf->SetFont('helvetica', 'B', 20);
        $pdf->Cell(0, 30, 'New Owner Handover', 0, 1, 'C');

        $pdf->SetFont('helvetica', 'B', 16);
        $pdf->Cell(0, 20, 'Puppy: ' . $animal['name'], 0, 1, 'C');

        $pdf->SetFont('helvetica', '', 12);
        $pdf->Cell(0, 10, 'Registration: ' . ($animal['registration_number'] ?: 'Not registered'), 0, 1, 'C');

        if ($animal['birth_date']) {
            $pdf->Cell(0, 10, 'Born: ' . date('F j, Y', strtotime($animal['birth_date'])), 0, 1, 'C');
        }

        $pdf->Ln(20);

        $pdf->SetFont('helvetica', '', 11);
        $pdf->MultiCell(0, 8, "Congratulations on your new family member!\n\nThis document contains important information about your puppy's pedigree, health history, and care requirements.", 0, 'C');
    }

    /**
     * Draw handover pedigree page
     */
    private static function draw_handover_pedigree($pdf, $animal) {
        $pdf->SetFont('helvetica', 'B', 16);
        $pdf->Cell(0, 20, 'Pedigree', 0, 1, 'C');

        // Simple pedigree display
        $pdf->SetFont('helvetica', 'B', 12);
        $pdf->Cell(0, 15, $animal['name'], 0, 1, 'C');

        $pdf->SetFont('helvetica', '', 10);
        $pdf->Cell(0, 10, 'Sire: ' . ($animal['sire_name'] ?: 'Unknown'), 0, 1, 'C');
        $pdf->Cell(0, 10, 'Dam: ' . ($animal['dam_name'] ?: 'Unknown'), 0, 1, 'C');
    }

    /**
     * Draw handover health history page
     */
    private static function draw_handover_health($pdf, $animal, $events) {
        $pdf->SetFont('helvetica', 'B', 16);
        $pdf->Cell(0, 20, 'Health History', 0, 1, 'C');

        if (empty($events)) {
            $pdf->SetFont('helvetica', '', 12);
            $pdf->Cell(0, 15, 'No health records available.', 0, 1, 'L');
            return;
        }

        $pdf->SetFont('helvetica', 'B', 10);
        $pdf->Cell(40, 8, 'Date', 1, 0, 'C');
        $pdf->Cell(40, 8, 'Type', 1, 0, 'C');
        $pdf->Cell(80, 8, 'Details', 1, 1, 'C');

        $pdf->SetFont('helvetica', '', 9);
        foreach ($events as $event) {
            $pdf->Cell(40, 7, date('M j, Y', strtotime($event['event_date'])), 1, 0, 'C');
            $pdf->Cell(40, 7, ucfirst($event['event_type']), 1, 0, 'C');
            $pdf->Cell(80, 7, substr($event['title'], 0, 30), 1, 1, 'L');
        }
    }

    /**
     * Draw handover care instructions page
     */
    private static function draw_handover_care($pdf, $animal) {
        $pdf->SetFont('helvetica', 'B', 16);
        $pdf->Cell(0, 20, 'Care Instructions', 0, 1, 'C');

        $feeding_instructions = get_option('truepaws_feeding_instructions', '');

        $pdf->SetFont('helvetica', '', 11);
        if ($feeding_instructions) {
            $pdf->MultiCell(0, 8, $feeding_instructions, 0, 'L');
        } else {
            $pdf->MultiCell(0, 8, "Please consult with your veterinarian for specific feeding recommendations based on your puppy's breed, age, and health needs.", 0, 'L');
        }

        $pdf->Ln(15);

        $pdf->SetFont('helvetica', 'B', 12);
        $pdf->Cell(0, 12, 'Important Reminders:', 0, 1, 'L');

        $pdf->SetFont('helvetica', '', 10);
        $reminders = array(
            'Schedule a veterinary check-up within the first week',
            'Maintain a consistent feeding schedule',
            'Provide plenty of fresh water',
            'Begin socialization and training early',
            'Keep up with vaccination and parasite prevention schedules'
        );

        foreach ($reminders as $reminder) {
            $pdf->Cell(5, 8, '•', 0, 0, 'L');
            $pdf->Cell(0, 8, $reminder, 0, 1, 'L');
        }
    }

    /**
     * Generate pedigree certificate PDF
     */
    public static function generate_pedigree_certificate($animal_id) {
        global $wpdb;

        // Get animal data
        $animal = $wpdb->get_row(
            $wpdb->prepare(
                "SELECT a.*, s.name as sire_name, d.name as dam_name
                 FROM {$wpdb->prefix}bm_animals a
                 LEFT JOIN {$wpdb->prefix}bm_animals s ON a.sire_id = s.id
                 LEFT JOIN {$wpdb->prefix}bm_animals d ON a.dam_id = d.id
                 WHERE a.id = %d",
                $animal_id
            ),
            ARRAY_A
        );

        if (!$animal) {
            return false;
        }

        // Get pedigree data
        $pedigree = truepaws_get_pedigree($animal_id, 3);

        $filename_base = 'pedigree-' . sanitize_title($animal['name']) . '-' . date('Y-m-d');

        // Try TCPDF first
        if (class_exists('TCPDF')) {
            try {
                $pdf = new TCPDF('P', 'mm', 'A4', true, 'UTF-8', false);
                $pdf->SetCreator('TruePaws');
                $pdf->SetAuthor(get_option('truepaws_breeder_name', ''));
                $pdf->SetTitle('Pedigree Certificate - ' . $animal['name']);
                $pdf->setPrintHeader(false);
                $pdf->setPrintFooter(false);
                $pdf->SetMargins(20, 20, 20);
                $pdf->SetAutoPageBreak(true, 20);
                $pdf->AddPage();

                self::draw_pedigree_certificate($pdf, $animal, $pedigree);

                $pdf_output = $pdf->Output($filename_base . '.pdf', 'S');

                return array(
                    'pdf' => base64_encode($pdf_output),
                    'filename' => $filename_base . '.pdf'
                );
            } catch (Exception $e) {
                // Fall through to HTML fallback
            }
        }

        // HTML fallback when TCPDF is not available
        $html = self::generate_pedigree_html($animal, $pedigree);

        if (self::is_dompdf_available()) {
            try {
                $dompdf = new \Dompdf\Dompdf();
                $dompdf->loadHtml($html);
                $dompdf->setPaper('A4', 'portrait');
                $dompdf->render();
                $pdf_output = $dompdf->output();

                return array(
                    'pdf' => base64_encode($pdf_output),
                    'filename' => $filename_base . '.pdf'
                );
            } catch (Exception $e) {
                // Fall through to raw HTML
            }
        }

        return array(
            'html' => $html,
            'filename' => $filename_base . '.html'
        );
    }

    /**
     * Generate pedigree certificate as styled HTML (fallback when no PDF library is available)
     */
    private static function generate_pedigree_html($animal, $pedigree) {
        $breeder_name = get_option('truepaws_breeder_name', '');
        $business_name = get_option('truepaws_business_name', '');

        $sire = !empty($pedigree['generations']['sire']) ? $pedigree['generations']['sire'] : null;
        $dam  = !empty($pedigree['generations']['dam'])  ? $pedigree['generations']['dam']  : null;

        $sire_sire = $sire && !empty($sire['descendants']['sire']) ? $sire['descendants']['sire'] : null;
        $sire_dam  = $sire && !empty($sire['descendants']['dam'])  ? $sire['descendants']['dam']  : null;
        $dam_sire  = $dam  && !empty($dam['descendants']['sire'])  ? $dam['descendants']['sire']  : null;
        $dam_dam   = $dam  && !empty($dam['descendants']['dam'])   ? $dam['descendants']['dam']   : null;

        $esc = function($v) { return htmlspecialchars($v ?: '', ENT_QUOTES, 'UTF-8'); };

        $cell = function($label, $data) use ($esc) {
            $name = $data ? $esc($data['name']) : 'Unknown';
            $reg  = ($data && !empty($data['registration_number'])) ? '<div class="cell-reg">' . $esc($data['registration_number']) . '</div>' : '';
            $breed_line = ($data && !empty($data['breed'])) ? '<div class="cell-breed">' . $esc($data['breed']) . '</div>' : '';
            return '<div class="ped-cell"><div class="cell-label">' . $esc($label) . '</div><div class="cell-name">' . $name . '</div>' . $reg . $breed_line . '</div>';
        };

        ob_start();
        ?>
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="UTF-8">
            <title>Pedigree Certificate - <?php echo $esc($animal['name']); ?></title>
            <style>
                * { margin: 0; padding: 0; box-sizing: border-box; }
                @page { size: A4 portrait; margin: 12mm; }
                body { font-family: 'Georgia', 'Times New Roman', serif; color: #2c2c2c; background: #fff; padding: 12mm; }
                .certificate { border: 3px double #8b7355; padding: 30px; min-height: 267mm; position: relative; }
                .header { text-align: center; margin-bottom: 25px; border-bottom: 2px solid #8b7355; padding-bottom: 20px; }
                .header h1 { font-size: 26px; letter-spacing: 3px; text-transform: uppercase; color: #4a3728; margin-bottom: 5px; }
                .header .subtitle { font-size: 12px; color: #8b7355; letter-spacing: 2px; text-transform: uppercase; }
                .animal-info { text-align: center; margin-bottom: 25px; }
                .animal-info h2 { font-size: 22px; color: #2c2c2c; margin-bottom: 10px; }
                .animal-info .meta { font-size: 11px; color: #666; line-height: 1.8; }
                .animal-info .meta span { margin: 0 8px; }
                .ped-title { text-align: center; font-size: 14px; font-weight: bold; color: #4a3728; margin-bottom: 15px; letter-spacing: 1px; text-transform: uppercase; }
                .ped-grid { display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 8px; margin-bottom: 25px; }
                .ped-cell { border: 1px solid #c9b99a; padding: 10px 8px; text-align: center; background: #fdfbf7; min-height: 60px; display: flex; flex-direction: column; justify-content: center; }
                .ped-cell.subject { grid-column: 1; grid-row: 1 / 5; background: #f5f0e6; border-color: #8b7355; border-width: 2px; }
                .ped-cell.parent { grid-column: 2; }
                .ped-cell.parent.sire { grid-row: 1 / 3; }
                .ped-cell.parent.dam { grid-row: 3 / 5; }
                .ped-cell.gp { grid-column: 3; }
                .cell-label { font-size: 9px; color: #8b7355; text-transform: uppercase; letter-spacing: 1px; margin-bottom: 4px; }
                .cell-name { font-weight: bold; font-size: 12px; }
                .cell-reg { font-size: 9px; color: #888; margin-top: 2px; font-style: italic; }
                .cell-breed { font-size: 9px; color: #999; margin-top: 1px; }
                .footer { position: absolute; bottom: 25px; left: 30px; right: 30px; text-align: center; font-size: 10px; color: #999; border-top: 1px solid #ddd; padding-top: 12px; }
                .footer .breeder { font-size: 11px; color: #666; margin-bottom: 4px; }
                @media print { body { padding: 0; } .certificate { border-width: 2px; } }
            </style>
        </head>
        <body>
            <div class="certificate">
                <div class="header">
                    <h1>Pedigree Certificate</h1>
                    <?php if ($business_name): ?>
                        <div class="subtitle"><?php echo $esc($business_name); ?></div>
                    <?php endif; ?>
                </div>

                <div class="animal-info">
                    <h2><?php echo $esc($animal['name']); ?></h2>
                    <div class="meta">
                        <?php if (!empty($animal['registration_number'])): ?>
                            <span>Reg: <?php echo $esc($animal['registration_number']); ?></span>
                        <?php endif; ?>
                        <?php if (!empty($animal['microchip_id'])): ?>
                            <span>Microchip: <?php echo $esc($animal['microchip_id']); ?></span>
                        <?php endif; ?>
                        <span>Breed: <?php echo $esc($animal['breed'] ?: 'Unknown'); ?></span>
                        <span>Sex: <?php echo $animal['sex'] === 'M' ? 'Male' : 'Female'; ?></span>
                        <?php if (!empty($animal['birth_date'])): ?>
                            <span>Born: <?php echo esc_html(date('F j, Y', strtotime($animal['birth_date']))); ?></span>
                        <?php endif; ?>
                    </div>
                </div>

                <div class="ped-title">Three Generation Pedigree</div>
                <div class="ped-grid">
                    <div class="ped-cell subject">
                        <div class="cell-label">Subject</div>
                        <div class="cell-name"><?php echo $esc($animal['name']); ?></div>
                        <?php if (!empty($animal['registration_number'])): ?>
                            <div class="cell-reg"><?php echo $esc($animal['registration_number']); ?></div>
                        <?php endif; ?>
                        <?php if (!empty($animal['breed'])): ?>
                            <div class="cell-breed"><?php echo $esc($animal['breed']); ?></div>
                        <?php endif; ?>
                    </div>

                    <div class="ped-cell parent sire"><?php
                        echo '<div class="cell-label">Sire</div>';
                        echo '<div class="cell-name">' . ($sire ? $esc($sire['name']) : 'Unknown') . '</div>';
                        if ($sire && !empty($sire['registration_number'])) echo '<div class="cell-reg">' . $esc($sire['registration_number']) . '</div>';
                    ?></div>

                    <div class="ped-cell gp"><?php
                        echo '<div class="cell-label">Paternal GS</div>';
                        echo '<div class="cell-name">' . ($sire_sire ? $esc($sire_sire['name']) : 'Unknown') . '</div>';
                        if ($sire_sire && !empty($sire_sire['registration_number'])) echo '<div class="cell-reg">' . $esc($sire_sire['registration_number']) . '</div>';
                    ?></div>
                    <div class="ped-cell gp"><?php
                        echo '<div class="cell-label">Paternal GD</div>';
                        echo '<div class="cell-name">' . ($sire_dam ? $esc($sire_dam['name']) : 'Unknown') . '</div>';
                        if ($sire_dam && !empty($sire_dam['registration_number'])) echo '<div class="cell-reg">' . $esc($sire_dam['registration_number']) . '</div>';
                    ?></div>

                    <div class="ped-cell parent dam"><?php
                        echo '<div class="cell-label">Dam</div>';
                        echo '<div class="cell-name">' . ($dam ? $esc($dam['name']) : 'Unknown') . '</div>';
                        if ($dam && !empty($dam['registration_number'])) echo '<div class="cell-reg">' . $esc($dam['registration_number']) . '</div>';
                    ?></div>

                    <div class="ped-cell gp"><?php
                        echo '<div class="cell-label">Maternal GS</div>';
                        echo '<div class="cell-name">' . ($dam_sire ? $esc($dam_sire['name']) : 'Unknown') . '</div>';
                        if ($dam_sire && !empty($dam_sire['registration_number'])) echo '<div class="cell-reg">' . $esc($dam_sire['registration_number']) . '</div>';
                    ?></div>
                    <div class="ped-cell gp"><?php
                        echo '<div class="cell-label">Maternal GD</div>';
                        echo '<div class="cell-name">' . ($dam_dam ? $esc($dam_dam['name']) : 'Unknown') . '</div>';
                        if ($dam_dam && !empty($dam_dam['registration_number'])) echo '<div class="cell-reg">' . $esc($dam_dam['registration_number']) . '</div>';
                    ?></div>
                </div>

                <div class="footer">
                    <?php if ($breeder_name): ?>
                        <div class="breeder">Breeder: <?php echo $esc($breeder_name); ?></div>
                    <?php endif; ?>
                    <div>Certificate generated on <?php echo date('F j, Y'); ?> &mdash; Powered by TruePaws</div>
                </div>
            </div>
        </body>
        </html>
        <?php
        return ob_get_clean();
    }

    /**
     * Draw pedigree certificate
     */
    private static function draw_pedigree_certificate($pdf, $animal, $pedigree) {
        // Header/Title
        $pdf->SetFont('helvetica', 'B', 24);
        $pdf->SetTextColor(51, 51, 51);
        $pdf->Cell(0, 20, 'PEDIGREE CERTIFICATE', 0, 1, 'C');

        // Border decoration
        $pdf->SetDrawColor(200, 200, 200);
        $pdf->SetLineWidth(0.5);
        $pdf->Rect(15, 15, 180, 267);

        $pdf->Ln(10);

        // Animal info
        $pdf->SetFont('helvetica', 'B', 18);
        $pdf->Cell(0, 15, $animal['name'], 0, 1, 'C');

        $pdf->SetFont('helvetica', '', 12);
        $pdf->SetTextColor(100, 100, 100);
        
        if (!empty($animal['registration_number'])) {
            $pdf->Cell(0, 8, 'Registration: ' . $animal['registration_number'], 0, 1, 'C');
        }
        
        if (!empty($animal['microchip_id'])) {
            $pdf->Cell(0, 8, 'Microchip: ' . $animal['microchip_id'], 0, 1, 'C');
        }

        $pdf->Cell(0, 8, 'Breed: ' . ($animal['breed'] ?: 'Unknown'), 0, 1, 'C');
        $pdf->Cell(0, 8, 'Sex: ' . ($animal['sex'] === 'M' ? 'Male' : 'Female'), 0, 1, 'C');
        
        if (!empty($animal['birth_date'])) {
            $pdf->Cell(0, 8, 'Born: ' . date('F j, Y', strtotime($animal['birth_date'])), 0, 1, 'C');
        }

        $pdf->Ln(15);

        // Pedigree tree
        $pdf->SetTextColor(51, 51, 51);
        $pdf->SetFont('helvetica', 'B', 14);
        $pdf->Cell(0, 12, 'Three Generation Pedigree', 0, 1, 'C');

        $pdf->SetFont('helvetica', '', 10);
        
        // Generation 1 (Parents)
        $y_start = $pdf->GetY() + 10;
        
        if (!empty($pedigree['generations']['sire'])) {
            $pdf->SetXY(100, $y_start);
            $pdf->Cell(80, 8, 'Sire: ' . $pedigree['generations']['sire']['name'], 0, 1, 'L');
            if (!empty($pedigree['generations']['sire']['registration_number'])) {
                $pdf->SetX(100);
                $pdf->SetFont('helvetica', 'I', 8);
                $pdf->Cell(80, 6, 'Reg: ' . $pedigree['generations']['sire']['registration_number'], 0, 1, 'L');
                $pdf->SetFont('helvetica', '', 10);
            }
        }

        $pdf->Ln(5);

        if (!empty($pedigree['generations']['dam'])) {
            $pdf->SetX(100);
            $pdf->Cell(80, 8, 'Dam: ' . $pedigree['generations']['dam']['name'], 0, 1, 'L');
            if (!empty($pedigree['generations']['dam']['registration_number'])) {
                $pdf->SetX(100);
                $pdf->SetFont('helvetica', 'I', 8);
                $pdf->Cell(80, 6, 'Reg: ' . $pedigree['generations']['dam']['registration_number'], 0, 1, 'L');
                $pdf->SetFont('helvetica', '', 10);
            }
        }

        $pdf->Ln(10);

        // Footer
        $pdf->SetY(-40);
        $pdf->SetFont('helvetica', 'I', 9);
        $pdf->SetTextColor(120, 120, 120);
        
        $breeder_name = get_option('truepaws_breeder_name', '');
        if ($breeder_name) {
            $pdf->Cell(0, 6, 'Breeder: ' . $breeder_name, 0, 1, 'C');
        }
        
        $pdf->Cell(0, 6, 'Certificate generated: ' . date('F j, Y'), 0, 1, 'C');
        $pdf->Cell(0, 6, 'Powered by TruePaws', 0, 1, 'C');
    }
}