<?php
/**
 * PDF Generator for TruePaws
 * Uses Dompdf to convert HTML to PDF
 */

if (!defined('ABSPATH')) {
    exit;
}

class TruePaws_PDF_Generator {

    /**
     * Check if Dompdf is available
     */
    public static function is_dompdf_available() {
        return class_exists('\Dompdf\Dompdf');
    }

    /**
     * Generate pedigree PDF
     * Note: For MVP, this creates a simple HTML-based pedigree that can be printed
     */
    public static function generate_pedigree_pdf($animal_id, $generations = 3) {
        $pedigree = truepaws_get_pedigree($animal_id, $generations);

        if (!$pedigree) {
            return false;
        }

        // For MVP, create HTML output that can be printed as PDF
        // In production, integrate with TCPDF or similar library
        ob_start();
        ?>
        <!DOCTYPE html>
        <html>
        <head>
            <title>Pedigree - <?php echo esc_html($pedigree['animal']['name']); ?></title>
            <style>
                body { font-family: Arial, sans-serif; margin: 20px; }
                .header { text-align: center; margin-bottom: 30px; }
                .pedigree-tree { display: flex; flex-direction: column; align-items: center; }
                .pedigree-generation { display: flex; justify-content: center; margin: 20px 0; }
                .pedigree-animal { border: 2px solid #333; padding: 10px; margin: 0 5px; text-align: center; min-width: 150px; }
                .pedigree-animal.main { border-color: #0066cc; background: #f0f7ff; }
                .animal-name { font-weight: bold; }
                .animal-reg { font-size: 12px; color: #666; }
                .footer { margin-top: 50px; text-align: center; font-size: 12px; color: #666; }
            </style>
        </head>
        <body>
            <div class="header">
                <h1>TruePaws Pedigree Certificate</h1>
                <h2><?php echo esc_html($pedigree['animal']['name']); ?></h2>
                <?php if (!empty($pedigree['animal']['registration_number'])): ?>
                    <p>Registration: <?php echo esc_html($pedigree['animal']['registration_number']); ?></p>
                <?php endif; ?>
                <?php if (!empty($pedigree['animal']['birth_date'])): ?>
                    <p>Born: <?php echo esc_html(date('F j, Y', strtotime($pedigree['animal']['birth_date']))); ?></p>
                <?php endif; ?>
            </div>

            <div class="pedigree-tree">
                <div class="pedigree-generation">
                    <div class="pedigree-animal main">
                        <div class="animal-name"><?php echo esc_html($pedigree['animal']['name']); ?></div>
                        <?php if (!empty($pedigree['animal']['registration_number'])): ?>
                            <div class="animal-reg"><?php echo esc_html($pedigree['animal']['registration_number']); ?></div>
                        <?php endif; ?>
                    </div>
                </div>

                <?php if (!empty($pedigree['generations']['sire']) || !empty($pedigree['generations']['dam'])): ?>
                <div class="pedigree-generation">
                    <div class="pedigree-animal">
                        <div class="animal-name">Sire</div>
                        <?php if (!empty($pedigree['generations']['sire'])): ?>
                            <div class="animal-name"><?php echo esc_html($pedigree['generations']['sire']['name']); ?></div>
                            <?php if (!empty($pedigree['generations']['sire']['registration_number'])): ?>
                                <div class="animal-reg"><?php echo esc_html($pedigree['generations']['sire']['registration_number']); ?></div>
                            <?php endif; ?>
                        <?php else: ?>
                            <div class="animal-name">Unknown</div>
                        <?php endif; ?>
                    </div>
                    <div class="pedigree-animal">
                        <div class="animal-name">Dam</div>
                        <?php if (!empty($pedigree['generations']['dam'])): ?>
                            <div class="animal-name"><?php echo esc_html($pedigree['generations']['dam']['name']); ?></div>
                            <?php if (!empty($pedigree['generations']['dam']['registration_number'])): ?>
                                <div class="animal-reg"><?php echo esc_html($pedigree['generations']['dam']['registration_number']); ?></div>
                            <?php endif; ?>
                        <?php else: ?>
                            <div class="animal-name">Unknown</div>
                        <?php endif; ?>
                    </div>
                </div>
                <?php endif; ?>
            </div>

            <div class="footer">
                <p>Generated by TruePaws Kennel Management System on <?php echo date('F j, Y \a\t g:i A'); ?></p>
                <p>Print this page to create a PDF pedigree certificate</p>
            </div>
        </body>
        </html>
        <?php

        $html = ob_get_clean();

        // For MVP, we'll output HTML that can be printed as PDF
        // In production, use a proper PDF library
        header('Content-Type: text/html');
        header('Content-Disposition: attachment; filename="pedigree-' . sanitize_title($pedigree['animal']['name']) . '-' . date('Y-m-d') . '.html"');
        echo $html;
        exit;
    }

    /**
     * Draw pedigree tree on PDF
     */
    private static function draw_pedigree_tree($pdf, $pedigree, $x = 10, $y = 60, $width = 180, $depth = 0) {
        $max_depth = 3;

        if ($depth > $max_depth) {
            return;
        }

        // Draw main animal box
        $pdf->SetFillColor(240, 240, 240);
        $pdf->Rect($x + $width/2 - 40, $y, 80, 20, 'DF');

        $pdf->SetFont('helvetica', 'B', 10);
        $pdf->SetXY($x + $width/2 - 35, $y + 2);
        $pdf->Cell(70, 5, substr($pedigree['animal']['name'], 0, 20), 0, 0, 'C');

        if ($depth < $max_depth) {
            // Draw parent boxes
            $parent_y = $y + 25;
            $parent_width = $width / 2;

            // Sire
            if (!empty($pedigree['generations']['sire'])) {
                self::draw_parent_box($pdf, $pedigree['generations']['sire'], $x, $parent_y, $parent_width, $depth + 1);
            } else {
                $pdf->Rect($x + 5, $parent_y, $parent_width - 10, 15);
                $pdf->SetXY($x + 10, $parent_y + 2);
                $pdf->Cell($parent_width - 20, 5, 'Unknown', 0, 0, 'C');
            }

            // Dam
            if (!empty($pedigree['generations']['dam'])) {
                self::draw_parent_box($pdf, $pedigree['generations']['dam'], $x + $parent_width, $parent_y, $parent_width, $depth + 1);
            } else {
                $pdf->Rect($x + $parent_width + 5, $parent_y, $parent_width - 10, 15);
                $pdf->SetXY($x + $parent_width + 10, $parent_y + 2);
                $pdf->Cell($parent_width - 20, 5, 'Unknown', 0, 0, 'C');
            }

            // Draw connecting lines
            $pdf->Line($x + $width/2, $y + 20, $x + $parent_width/2, $parent_y);
            $pdf->Line($x + $width/2, $y + 20, $x + $parent_width + $parent_width/2, $parent_y);
        }
    }

    /**
     * Draw parent box recursively
     */
    private static function draw_parent_box($pdf, $animal, $x, $y, $width, $depth) {
        $pdf->Rect($x + 5, $y, $width - 10, 15);
        $pdf->SetXY($x + 10, $y + 2);
        $pdf->SetFont('helvetica', '', 8);
        $pdf->Cell($width - 20, 4, substr($animal['name'], 0, 15), 0, 1, 'C');

        if (!empty($animal['registration_number'])) {
            $pdf->SetXY($x + 10, $y + 6);
            $pdf->SetFont('helvetica', '', 6);
            $pdf->Cell($width - 20, 3, substr($animal['registration_number'], 0, 20), 0, 0, 'C');
        }

        // Recursively draw grandparents if they exist
        if ($depth < 3 && (!empty($animal['descendants']['sire']) || !empty($animal['descendants']['dam']))) {
            $grandparent_y = $y + 18;
            $grandparent_width = $width / 2;

            // Draw grandparents (simplified)
            if (!empty($animal['descendants']['sire'])) {
                $pdf->Rect($x + 8, $grandparent_y, $grandparent_width - 11, 12);
                $pdf->SetXY($x + 10, $grandparent_y + 1);
                $pdf->SetFont('helvetica', '', 6);
                $pdf->Cell($grandparent_width - 15, 3, substr($animal['descendants']['sire']['name'], 0, 12), 0, 0, 'C');
            }

            if (!empty($animal['descendants']['dam'])) {
                $pdf->Rect($x + $grandparent_width + 3, $grandparent_y, $grandparent_width - 11, 12);
                $pdf->SetXY($x + $grandparent_width + 5, $grandparent_y + 1);
                $pdf->SetFont('helvetica', '', 6);
                $pdf->Cell($grandparent_width - 15, 3, substr($animal['descendants']['dam']['name'], 0, 12), 0, 0, 'C');
            }
        }
    }

    /**
     * Generate handover PDF
     * For MVP, creates HTML that can be printed as PDF
     */
    public static function generate_handover_pdf($animal_id) {
        global $wpdb;

        // Get animal data
        $animal = $wpdb->get_row(
            $wpdb->prepare(
                "SELECT A.*, S.name as sire_name, D.name as dam_name
                 FROM {$wpdb->prefix}bm_animals A
                 LEFT JOIN {$wpdb->prefix}bm_animals S ON A.sire_id = S.id
                 LEFT JOIN {$wpdb->prefix}bm_animals D ON A.dam_id = D.id
                 WHERE A.id = %d",
                $animal_id
            ),
            ARRAY_A
        );

        if (!$animal) {
            return false;
        }

        // Get health history (events)
        $events = $wpdb->get_results(
            $wpdb->prepare(
                "SELECT * FROM {$wpdb->prefix}bm_events
                 WHERE animal_id = %d AND event_type IN ('vaccine', 'vet_visit', 'heat', 'weight', 'birth')
                 ORDER BY event_date DESC",
                $animal_id
            ),
            ARRAY_A
        );

        ob_start();
        ?>
        <!DOCTYPE html>
        <html>
        <head>
            <title>Owner Handover - <?php echo esc_html($animal['name']); ?></title>
            <style>
                body { font-family: Arial, sans-serif; margin: 0; padding: 20px; line-height: 1.6; }
                .header { text-align: center; border-bottom: 2px solid #0066cc; padding-bottom: 20px; margin-bottom: 30px; }
                .section { margin-bottom: 30px; }
                .section h2 { color: #0066cc; border-bottom: 1px solid #ddd; padding-bottom: 5px; }
                .animal-info { background: #f8f9fa; padding: 15px; margin: 20px 0; }
                .health-table { width: 100%; border-collapse: collapse; margin: 20px 0; }
                .health-table th, .health-table td { border: 1px solid #ddd; padding: 8px; text-align: left; }
                .health-table th { background: #f8f9fa; font-weight: bold; }
                .pedigree { text-align: center; margin: 20px 0; }
                .footer { margin-top: 50px; text-align: center; font-size: 12px; color: #666; border-top: 1px solid #ddd; padding-top: 20px; }
                .print-note { background: #fff3cd; border: 1px solid #ffeeba; padding: 15px; margin: 20px 0; }
            </style>
        </head>
        <body>
            <div class="header">
                <h1>TruePaws Owner Handover</h1>
                <h2>Puppy: <?php echo esc_html($animal['name']); ?></h2>
                <p>Handover Date: <?php echo date('F j, Y'); ?></p>
            </div>

            <div class="section animal-info">
                <h2>Animal Information</h2>
                <p><strong>Name:</strong> <?php echo esc_html($animal['name']); ?></p>
                <?php if (!empty($animal['call_name'])): ?>
                    <p><strong>Call Name:</strong> <?php echo esc_html($animal['call_name']); ?></p>
                <?php endif; ?>
                <p><strong>Breed:</strong> <?php echo esc_html($animal['breed'] ?: 'Not specified'); ?></p>
                <p><strong>Sex:</strong> <?php echo $animal['sex'] === 'M' ? 'Male' : 'Female'; ?></p>
                <?php if (!empty($animal['birth_date'])): ?>
                    <p><strong>Date of Birth:</strong> <?php echo esc_html(date('F j, Y', strtotime($animal['birth_date']))); ?></p>
                <?php endif; ?>
                <?php if (!empty($animal['registration_number'])): ?>
                    <p><strong>Registration:</strong> <?php echo esc_html($animal['registration_number']); ?></p>
                <?php endif; ?>
                <p><strong>Sire:</strong> <?php echo esc_html($animal['sire_name'] ?: 'Unknown'); ?></p>
                <p><strong>Dam:</strong> <?php echo esc_html($animal['dam_name'] ?: 'Unknown'); ?></p>
            </div>

            <div class="section pedigree">
                <h2>Pedigree</h2>
                <div style="font-family: monospace; background: #f8f9fa; padding: 20px;">
                    <div><?php echo esc_html($animal['name']); ?></div>
                    <div style="margin-top: 10px;">
                        <span>Sire: <?php echo esc_html($animal['sire_name'] ?: 'Unknown'); ?></span>
                        <span style="margin-left: 20px;">Dam: <?php echo esc_html($animal['dam_name'] ?: 'Unknown'); ?></span>
                    </div>
                </div>
                <p><em>For complete 3-4 generation pedigree, see attached pedigree certificate.</em></p>
            </div>

            <div class="section">
                <h2>Health History</h2>
                <?php if (!empty($events)): ?>
                    <table class="health-table">
                        <thead>
                            <tr>
                                <th>Date</th>
                                <th>Event Type</th>
                                <th>Details</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($events as $event): ?>
                                <tr>
                                    <td><?php echo esc_html(date('M j, Y', strtotime($event['event_date']))); ?></td>
                                    <td><?php echo esc_html(ucfirst(str_replace('_', ' ', $event['event_type']))); ?></td>
                                    <td><?php echo esc_html($event['title']); ?></td>
                                </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                <?php else: ?>
                    <p>No health records available yet.</p>
                <?php endif; ?>
            </div>

            <div class="section">
                <h2>Care Instructions</h2>
                <?php
                $feeding_instructions = get_option('truepaws_feeding_instructions', '');
                if ($feeding_instructions):
                ?>
                    <div style="background: #f8f9fa; padding: 15px; margin: 20px 0;">
                        <?php echo wp_kses_post($feeding_instructions); ?>
                    </div>
                <?php else: ?>
                    <p>Please consult with your veterinarian for specific feeding recommendations based on your puppy's breed, age, and health needs.</p>
                <?php endif; ?>

                <h3>General Care Recommendations:</h3>
                <ul>
                    <li>Schedule a veterinary check-up within the first week</li>
                    <li>Maintain a consistent feeding schedule</li>
                    <li>Provide plenty of fresh water</li>
                    <li>Begin socialization and training early</li>
                    <li>Keep up with vaccination and parasite prevention schedules</li>
                    <li>Provide appropriate exercise and mental stimulation</li>
                </ul>
            </div>

            <div class="section">
                <h2>Contract & Terms</h2>
                <div style="background: #f8f9fa; padding: 20px; border-left: 4px solid #0066cc;">
                    <p><strong>Health Guarantee:</strong> This puppy is guaranteed to be in good health at the time of sale. Any congenital health issues will be addressed according to our health guarantee policy.</p>

                    <p><strong>Return Policy:</strong> If for any reason you cannot keep this puppy, please contact us immediately. We will work with you to find a suitable solution.</p>

                    <p><strong>Support:</strong> We are here to support you throughout your puppy's life. Please don't hesitate to contact us with any questions or concerns.</p>

                    <p><strong>Agreement:</strong> By accepting this puppy, you agree to provide proper care, veterinary attention, and a loving home.</p>
                </div>
            </div>

            <div class="footer">
                <p>Generated by TruePaws Kennel Management System on <?php echo date('F j, Y \a\t g:i A'); ?></p>
                <p>Thank you for choosing our kennel!</p>
            </div>
        </body>
        </html>
        <?php

        $html = ob_get_clean();

        if (self::is_dompdf_available()) {
            try {
                $dompdf = new \Dompdf\Dompdf();
                $dompdf->loadHtml($html);
                $dompdf->setPaper('A4', 'portrait');
                $dompdf->render();
                $pdf_output = $dompdf->output();

                return array(
                    'pdf' => base64_encode($pdf_output),
                    'filename' => 'handover-' . sanitize_title($animal['name']) . '-' . date('Y-m-d') . '.pdf'
                );
            } catch (Exception $e) {
                // Fallback to HTML if PDF generation fails
                return array(
                    'html' => $html,
                    'filename' => 'handover-' . sanitize_title($animal['name']) . '-' . date('Y-m-d') . '.html'
                );
            }
        }

        return array(
            'html' => $html,
            'filename' => 'handover-' . sanitize_title($animal['name']) . '-' . date('Y-m-d') . '.html'
        );
    }

    /**
     * Draw handover cover page
     */
    private static function draw_handover_cover($pdf, $animal) {
        // Title
        $pdf->SetFont('helvetica', 'B', 20);
        $pdf->Cell(0, 30, 'New Owner Handover', 0, 1, 'C');

        $pdf->SetFont('helvetica', 'B', 16);
        $pdf->Cell(0, 20, 'Puppy: ' . $animal['name'], 0, 1, 'C');

        $pdf->SetFont('helvetica', '', 12);
        $pdf->Cell(0, 10, 'Registration: ' . ($animal['registration_number'] ?: 'Not registered'), 0, 1, 'C');

        if ($animal['birth_date']) {
            $pdf->Cell(0, 10, 'Born: ' . date('F j, Y', strtotime($animal['birth_date'])), 0, 1, 'C');
        }

        $pdf->Ln(20);

        $pdf->SetFont('helvetica', '', 11);
        $pdf->MultiCell(0, 8, "Congratulations on your new family member!\n\nThis document contains important information about your puppy's pedigree, health history, and care requirements.", 0, 'C');
    }

    /**
     * Draw handover pedigree page
     */
    private static function draw_handover_pedigree($pdf, $animal) {
        $pdf->SetFont('helvetica', 'B', 16);
        $pdf->Cell(0, 20, 'Pedigree', 0, 1, 'C');

        // Simple pedigree display
        $pdf->SetFont('helvetica', 'B', 12);
        $pdf->Cell(0, 15, $animal['name'], 0, 1, 'C');

        $pdf->SetFont('helvetica', '', 10);
        $pdf->Cell(0, 10, 'Sire: ' . ($animal['sire_name'] ?: 'Unknown'), 0, 1, 'C');
        $pdf->Cell(0, 10, 'Dam: ' . ($animal['dam_name'] ?: 'Unknown'), 0, 1, 'C');
    }

    /**
     * Draw handover health history page
     */
    private static function draw_handover_health($pdf, $animal, $events) {
        $pdf->SetFont('helvetica', 'B', 16);
        $pdf->Cell(0, 20, 'Health History', 0, 1, 'C');

        if (empty($events)) {
            $pdf->SetFont('helvetica', '', 12);
            $pdf->Cell(0, 15, 'No health records available.', 0, 1, 'L');
            return;
        }

        $pdf->SetFont('helvetica', 'B', 10);
        $pdf->Cell(40, 8, 'Date', 1, 0, 'C');
        $pdf->Cell(40, 8, 'Type', 1, 0, 'C');
        $pdf->Cell(80, 8, 'Details', 1, 1, 'C');

        $pdf->SetFont('helvetica', '', 9);
        foreach ($events as $event) {
            $pdf->Cell(40, 7, date('M j, Y', strtotime($event['event_date'])), 1, 0, 'C');
            $pdf->Cell(40, 7, ucfirst($event['event_type']), 1, 0, 'C');
            $pdf->Cell(80, 7, substr($event['title'], 0, 30), 1, 1, 'L');
        }
    }

    /**
     * Draw handover care instructions page
     */
    private static function draw_handover_care($pdf, $animal) {
        $pdf->SetFont('helvetica', 'B', 16);
        $pdf->Cell(0, 20, 'Care Instructions', 0, 1, 'C');

        $feeding_instructions = get_option('truepaws_feeding_instructions', '');

        $pdf->SetFont('helvetica', '', 11);
        if ($feeding_instructions) {
            $pdf->MultiCell(0, 8, $feeding_instructions, 0, 'L');
        } else {
            $pdf->MultiCell(0, 8, "Please consult with your veterinarian for specific feeding recommendations based on your puppy's breed, age, and health needs.", 0, 'L');
        }

        $pdf->Ln(15);

        $pdf->SetFont('helvetica', 'B', 12);
        $pdf->Cell(0, 12, 'Important Reminders:', 0, 1, 'L');

        $pdf->SetFont('helvetica', '', 10);
        $reminders = array(
            'Schedule a veterinary check-up within the first week',
            'Maintain a consistent feeding schedule',
            'Provide plenty of fresh water',
            'Begin socialization and training early',
            'Keep up with vaccination and parasite prevention schedules'
        );

        foreach ($reminders as $reminder) {
            $pdf->Cell(5, 8, '•', 0, 0, 'L');
            $pdf->Cell(0, 8, $reminder, 0, 1, 'L');
        }
    }
}